version: "3"
services:
  auth-db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "6000:5432"
  account-db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=account
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "6001:5432"
  inventory-db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=inventory
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "6002:5432"
  order-db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "6003:5432"
  payment-db:
    image: postgres:15.0
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "6004:5432"
  redis:
    image: redis:7.0.5-alpine3.16
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.11.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
