apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: solidvessel
  labels:
    app: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apache-apisix
        image: apache/apisix:3.13.0-debian
        env:
        - name: APISIX_STAND_ALONE
          value: "true"
        envFrom:
        - secretRef:
            name: apisix-secret
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: apisix-conf-volume
          mountPath: /usr/local/apisix/conf/apisix.yaml
          subPath: apisix.yaml
        - name: apisix-conf-volume
          mountPath: /usr/local/apisix/conf/config.yaml
          subPath: config.yaml
      volumes:
      - name: apisix-conf-volume
        configMap:
          name: apisix-conf
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet