apiVersion: v1
kind: Service
metadata:
  name: account-db-postgresql
  namespace: microshop
spec:
  type: NodePort
  selector:
    db: account
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32001